version: '2'
services:
  serve:
    image: teracy/angular-boilerplate
    container_name: cinema_angular
    command: ng serve --host 0.0.0.0
    environment:
      NODE_ENV: development
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - "4200:4200"
